name: Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'  # daily noon UTC
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Override remote URL with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}

      - name: Commit changes and push
        run: |
          echo "Ping: $(date)" > timestamp.txt
          git add timestamp.txt
          git commit -m "🤖 daily ping" || echo "No changes to commit"
          git push origin HEAD:main
