# .github/workflows/autocommit.yml

name: Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'  # every day at noon UTC
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make a dummy commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          date > timestamp.txt
          git add .
          git commit -m "🤖 daily ping" || echo "nothing to commit"
          git push
