# .github/workflows/autocommit.yml

name: Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'  # every day at noon UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  autocommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Make a dummy commit
        run: |
          echo "Ping: $(date)" > timestamp.txt
          git add timestamp.txt
          git commit -m "🤖 daily ping" || echo "nothing to commit"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push
        env:
          PAT: ${{ secrets.PAT }}
